# Generated by Django 6.0 on 2025-12-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutPlan',
        ),
    ]
